[package]
name = "db-migration"
version = "0.1.0"
authors = ["Lei Wang <wl1434351332@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "*"
